### ISSUE TITLE
No setup action

### ISSUE THREAD

**Issue by archspangler** [domeger/SplunkTAforPuppetEnterprise#1]
I am not seeing the Setup action\page when I attempt to follow the documentation step "open the Setup page from the Manage Apps page to configure your Puppet Enterprise server info"

I do not see the Setup action button to click in the Splunk GUI.

Is there an example of the inputs.conf that can be modified for our Puppet Enterprise server and credentials?

**Comment by domeger** [comment]
If you go into the Puppet Technical Addon, it has each section of the data input. If you want I can take screenshots of each as an example if that helps you accelerate your usage. @archspangler . Email me at deger@splunk.com for your email and ill mail them over.

**Comment by archspangler** [comment]
Screenshots would be helpful or just a sample inputs.conf file.

Thanks

**Comment by domeger** [comment]
![slide1](https://user-images.githubusercontent.com/4328119/31129154-98567e12-a808-11e7-92ac-27f9703aae1a.jpg)
![slide2](https://user-images.githubusercontent.com/4328119/31129157-986db866-a808-11e7-9282-dfd45509c0ac.jpg)
![slide3](https://user-images.githubusercontent.com/4328119/31129155-985a0032-a808-11e7-8de7-565f824c9406.jpg)
![slide4](https://user-images.githubusercontent.com/4328119/31129156-98670ce6-a808-11e7-942b-c4225dc2f9b7.jpg)

Example Inputs.conf

[puppet_enterprise_aggregate_details_resources]
index = default
start_by_shell = false
sourcetype = pe:aggdetails
interval = 60
port = 8080
summarize_by = resource
 
[puppet_enterprise_aggregate_details_classes]
index = default
start_by_shell = false
sourcetype = pe:aggdetails:classes
interval = 60
port = 8080
summarize_by = containing_class
 
[puppet_enterprise_nodes]
index = default
start_by_shell = false
sourcetype = pe:nodes
interval = 60
 
[pe_status]
index = default
start_by_shell = false
sourcetype = pe:status
interval = 60
 
[puppet_enterprise_aggregate_details_certname]
index = default
start_by_shell = false
sourcetype = pe:aggdetails:certname
interval = 60
port = 8080
summarize_by = certname
 
[puppet_enterprise_facts]
index = default
start_by_shell = false
sourcetype = pe:facts
interval = 300
 
[puppet_events_extended_details]
index = default
start_by_shell = false
sourcetype = pe:events:extdetails
interval = 300
port = 8080
 
[puppet_events_extended_details://Puppet_Events_Extended_Details]
interval = 60
port = 8080
server = http://10.1.2.206
 
 
[puppet_enterprise_aggregate_details_resources://Puppet_Agg_Details]
summarize_by = resource
interval = 3600
port = 8080
server = http://10.1.2.206
 
[puppet_enterprise_aggregate_details_certname://Puppet_Enterprise_Aggregate_Details_Certname]
summarize_by = certname
interval = 60
port = 8080
server = http://10.1.2.206
 
[puppet_enterprise_facts://Puppet_Enterprise_Facts]
port = 8080
interval = 120
type_of_environment = production
server = http://10.1.2.206
 
[puppet_enterprise_nodes://Puppet_Enterprise_Node_Status]
interval = 60
port = 8080
server = http://10.1.2.206
 
[puppet_enterprise_aggregate_details_classes://Puppet_Enterprise_Aggregrate_Details]
summarize_by = containing_class
interval = 60
port = 8080
server = http://10.1.2.206
 
[puppet_enterprise_aggregate_details_certname://Puppet_Enterprise_Aggregate_Details]
summarize_by = certname
interval = 60
port = 8080
server = http://10.1.2.206
 
[puppet_enterprise_aggregate_details_resources://Puppet_Enterprise_Aggregate_Details_Resources]
summarize_by = resource
interval = 60
port = 8080
server = http://10.1.2.206
 
[pe_status://Puppet_Enterprise_Status]
interval = 60
port = 8080
server = 10.1.2.206

**Comment by archspangler** [comment]
Here is what I see from the CLI...

-bash-4.1$ pwd

/opt/splunk/etc/apps

-bash-4.1$ ls | grep -i puppet

SplunkAppforPuppetEnterprise

SplunkTAforPuppetEnterprise


But the GUI show the same application name (See screenshot)??

**Comment by domeger** [comment]
Emailed you SPL Packages, let me know if that fixes your issues.
