### ISSUE TITLE
Can't get it to work at all

### ISSUE THREAD

**Issue by rvdlinden** [domeger/SplunkTAforPuppetEnterprise#2]
I have installed a client Splunk 7.0 server, and also a 6.3.12, and installed the Add on and the App for Puppet.

On either server version the SplunkTA drops errors in /opt/splunk/var/log/splunk

HTTPError: HTTP 500 Internal Server Error -- {"messages":[{"type":"ERROR","text":"\n In handler 'SplunkTAforPuppetEnterprise_settings': Unexpected error \"<class 'splunktaucclib.rest_handler.error.RestError'>\" from python handler: \"REST Error [500]: Internal Server Error -- Traceback (most recent call last):\n  File \"/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/splunktaforpuppetenterprise/splunktaucclib/rest_handler/handler.py\", line 113, in wrapper\n    for name, data, acl in meth(self, *args, **kwargs):\n  File \"/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/splunktaforpuppetenterprise/splunktaucclib/rest_handler/handler.py\", line 299, in _format_response\n    masked = self.rest_credentials.decrypt_for_get(name, data)\n  File \"/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/splunktaforpuppetenterprise/splunktaucclib/rest_handler/credentials.py\", line 184, in decrypt_for_get\n    clear_password = self._get(name)\n  File \"/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/splunktaforpuppetenterprise/splunktaucclib/rest_handler/credentials.py\", line 389, in _get\n    string = mgr.get_password(user=context.username())\n  File \"/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/splunktaforpuppetenterprise/solnlib/utils.py\", line 154, in wrapper\n    return func(*args, **kwargs)\n  File \"/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/splunktaforpuppetenterprise/solnlib/credentials.py\", line 118, in get_password\n    all_passwords = self._get_all_passwords()\n  File \"/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/splunktaforpuppetenterprise/solnlib/utils.py\", line 154, in wrapper\n    return func(*args, **kwargs)\n  File \"/opt/splunk/etc/apps/SplunkTAforPuppetEnterprise/bin/splunktaforpuppetenterprise/solnlib/credentials.py\", line 272, in _get_all_passwords\n    clear_password += field_clear[index]\nTypeError: cannot concatenate 'str' and 'NoneType' objects\n\".  See splunkd.log for more details."}]}

My steps (RHEL 7.4)

1. Install splunk server (7.0 and/or 6.3.12)
2. Cd /opt/splunk/etc/apps
3. Git clone https://github.com/domeger/SplunkAppforPuppetEnterprise.git SplunkAppforPuppetEnterprise
4. Git clone https://github.com/domeger/SplunkTAforPuppetEnterprise.git SplunkTAforPuppetEnterprise
5. Configure real puppet server and replace default http://x.x.x.x for all inputs
6. Restart splunk

NOTE: PE is listening on 0.0.0.0:8080

Regards,
Rene

**Comment by domeger** [comment]
Did you remove the local folder after you cloned?,  the local folder was left in there for reference for inputs.conf but I can add that to the instructions. This error is just saying it cant reference the encrypted password. I will also test your version of RHEL and see if it the same issue. Have not tested it with Version Splunk 7.0 yet.

**Comment by rvdlinden** [comment]
Hi Domnick,

I did not remove anything after the clone.
Just clone, configure PE server and watched the errors :-(

Regards
Rene


Op 29 november 2017 20:32:51 schreef Domnick Eger <notifications@github.com>:

**Comment by domeger** [comment]
I am at AWS Reinvent right now, as soon as I get back into the office I will start troubleshooting this.

**Comment by andrewm3** [comment]
Removing the `passwords.conf` resolved the issue for me.

**Comment by rvdlinden** [comment]
Fixed :-), by removing pwd file
