### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by archspangler** [domeger/SplunkTAforPuppetEnterprise#5]
I am using Splunk 7.2.1 and I am never able to get to the GUI items to enter the api_token or configure the servername \ ports for the inputs.   

When I click on the App in the GUI I get a "500 Server Error" with a horse saying "Oops"..

-Archie

**Comment by domeger** [comment]
Apologize for the delay, I am about to release an update to this Addon + App, but are you keeping the directory name the same?  SplunkTAforPuppetEnterprise

I tested on 7.2 recently and it did not fail to load.

**Comment by archspangler** [comment]
Yes, I am keeping the directory name the same.  I am just untaring into the apps folder and restarting Splunkd.  I even tried on a "fresh" installation (7.2.1) and I get the same error.   I am running splunkd as "splunk"... not "root".

-Archie

**Comment by archspangler** [comment]
I took a second look..  I see that my directory name is SplunkTAforPuppetEnterprise-master..  I renamed the directory to SplunkTAforPuppetEnterprise and now I am not getting the error.  I will continue with the configurations now.
