### ISSUE TITLE
Not getting any logs from "extended details"

### ISSUE THREAD

**Issue by hettervik** [domeger/SplunkTAforPuppetEnterprise#6]
Hi,

I've sat up the Puppet TA, generated the token, and configured the inputs on a Splunk HF. Most of them works fine, and we're getting data into Splunk, but for one of the inputs we're not getting any data. The faulty input is namely the one for "extended details".

I've looked through the internal logs, but cant find any help there. The only message I'm getting in the internal Puppet TA log is the following.

`"timestamp" ERROR pid=12345 tid=MainThread file=base_modinput.py:log_error:307 | []`

This error I'm getting from the source `/opt/splunk/var/log/splunk/splunkta/forpuppetenterprise_puppet_enterprise_extended_details.log`.

Any idea on why it fails just for this one input, and how I could get some more insightful error messages on the subject?

**Comment by domeger** [comment]
Can you provide what version of PE you are using?, so I can recreate the issue.

**Comment by domeger** [comment]
I am thinking about adding a factor filter what default one would you like to see ? Also Ill add the ssl ca cert option to make it easier to install.  Will update the docs.  I had it in version 1 and must have be a type.

**Comment by hettervik** [comment]
I will check out what version of PE we're using. I can't check it myself, so I'll get back to you on that tomorrow.

About the factor filter; I'm not sure. I'm not a Puppet admin, so I don't know what information is the most relevant. That being said, I talked with a colleague of mine today, an he said the "factors" your talking about should probably be named "facts". Could this be correct, that this name is a typo in the app and TA?

**Comment by hettervik** [comment]
The version of PE we're using is v2018.1.2.

**Comment by domeger** [comment]
I just installed the newest version of Puppet, will start working on this issue.

**Comment by domeger** [comment]
I have uploaded the latest version that is working on the latest version of Puppet Enterprise and Splunk. Should resolve some of these issues that you are having, you will need to reset your inputs.

**Comment by hettervik** [comment]
Thanks for updating the TA! I've downloaded it, and tried gettting it to work, but have ran into some new problems, unfortunately.

1. In some of the python scripts the "pe_link" variable is not defined. I've manually added a line to the script that set the pe_link variable to the puppet server url, which it fetches from the input stanza. If you don't edit the script manually it won't work, and you get error messages.

2. There is now several error messages when starting the Splunk instance that there are invalid keys in stanzas. The stanzas are the ones from the inputs.conf in the default folder. Are the inputs in default/inputs.conf examples? If so, perhaps they could be commented out? (EDIT: commenting out the stanzas at least got rid of the error messages related to this) (when commenting out the stanzas, the default port is removed from most of the inputs and has to be added again manually)

3. If you install the TA straight from the GUI you get an 500 internal server error. This is because Git adds a "-master" postfix to the folder name. Perhaps it's possible to make it so that this postfix isn't added?

4. I still get a lot of error messages with `py:log_error:307`. Some of these error messages doesn't seem like they should be error messages at all, as all they contain is exact copies of the events indexed, as far as I can tell.

Sorry I cant copy in examples and screens. I work on a closed net, and I can't bring any data out of the net.

EDIT: It seems you have fixed point 1 already, from what I can tell looking at your repo.

EDIT2: I still don't get any data from "extended inputs", and I get the exact same error message as in my first post - with no further input.

**Comment by domeger** [comment]
@hettervik did you remove your inputs and recreate them via the Add-on?,  Number 3 can easily be fixed when you do "git clone https://github.com/domeger/SplunkTAforPuppetEnterprise.git ." while your in the /opt/splunk/etc/apps/ directory.

I had to modify a good chunk of the app to support multiple PE Master per customer request so that modified how each pull is done. I have tested this on the last three release so the extended should work fine if you reset the inputs.

**Comment by archspangler** [comment]
I am also getting a lot of 307 errors in the splunktaforpuppetenterprise_puppet_enterprise_extended_details.log.

2018-09-27 08:27:00,327 ERROR pid=23709 tid=MainThread file=base_modinput.py:log_error:307 | []
2018-09-27 08:30:35,004 ERROR pid=25280 tid=MainThread file=base_modinput.py:log_error:307 | []
2018-09-27 08:32:00,244 ERROR pid=26508 tid=MainThread file=base_modinput.py:log_error:307 | []
2018-09-27 08:35:35,022 ERROR pid=28243 tid=MainThread file=base_modinput.py:log_error:307 | []

How are you handling timestamps with the extended events; or really all of the events sourcetypes from PE?  All the date/times from PE are in GMT so I think my events are getting ingested in the future; I need to verify.  Are you just letting splunk add the timestamps of when it's ingested?

-Archie

**Comment by domeger** [comment]
If you look at the checkpoint creation, this is based on Puppet Timestamp. There is an index time that is tagged to each pull but I am also using the Puppet timestamps to pull.

 if ckpt_value == None:
        old = now - datetime.timedelta(minutes=5)
        #format the time
        # This is a timestamp in UTC-based ISO-8601 format (YYYY-MM-DDThh:mm:ssZ) 
        start_time = old.strftime("%Y-%m-%dT%H:%M:%SZ") 
    #if it does exist then checkpoint value is start time
    else:
        start_time=ckpt_value
    end_time=now.strftime("%Y-%m-%dT%H:%M:%SZ") 


![facts](https://user-images.githubusercontent.com/4328119/46157594-f0dc7a80-c230-11e8-9c70-18673ce40bb3.PNG)

**Comment by archspangler** [comment]
Our extended_events are in the future..  I traced one of our event all the way back to the host..

Here is the actual event in /var/log/messages on the agent..  Times are EST GMT-4.
Notice the catalog times.

![image](https://user-images.githubusercontent.com/32362414/46219540-9bc66480-c315-11e8-8b77-5835bdc7def2.png)


![image](https://user-images.githubusercontent.com/32362414/46219144-91579b00-c314-11e8-99f0-3ce8a97ce057.png)


Same event on Splunk: Note the report GUID : 986868821df1df769b233f326f285c0407e4064c	 

![image](https://user-images.githubusercontent.com/32362414/46218779-84867780-c313-11e8-8d2c-c7485231a182.png)

![image](https://user-images.githubusercontent.com/32362414/46219473-79344b80-c315-11e8-98e2-93fe90875ef0.png)


Event in PE console: (Same report GUID)

![image](https://user-images.githubusercontent.com/32362414/46218830-a253dc80-c313-11e8-9056-f48bf200ce6b.png)

In PE, I notice when you mouseover the dates\times that are always shown in GMT, they will present the timezone offset of the actual time.  (I don't like how Puppet does this).

I would prefer to see my events in Splunk with my local timezone.  I am not seeing events that happen @now until 4 hours later.

-Archie

**Comment by domeger** [comment]
@archspangler - Will experiment and see what I can do to adjust this. I will also consult the puppet team and see if you can change the report times.

**Comment by mrzarquon** [comment]
> In PE, I notice when you mouseover the dates\times that are always shown in GMT, they will present the timezone offset of the actual time. (I don't like how Puppet does this).
> 
> I would prefer to see my events in Splunk with my local timezone. I am not seeing events that happen @now until 4 hours later.
> 
> -Archie

You can change that in the console settings - https://puppet.com/docs/pe/2018.1/config_console.html#console-and-console-services-parameters

go to Classifier -> PE Inf -> PE Console -> Configuration -> and add "display_local_time" -> True to the 'puppet_enterprise::profile::console' class. This will flip the behavior and display the local time in the UI with the UTC time in the mouseover.

Note: Puppet will log events in UTC since multiregion/timezones/daylightsavings are annoying, so we just have the UI render them in local time of the browser.

**Comment by archspangler** [comment]
@mrzarquon That worked great!   Thanks for the PE tip!!

-Archie

**Comment by hettervik** [comment]
Hi folks. Taking this thread back to the original question at hand. After doing quite some reverse engineering and troubleshooting, I think I've pinned down the root cause to why we're not getting any data from the extended details input.

In the bin catalog of the TA there is a script named `input_module_puppet_enterprise_extended_details.py`. It is this file that contains the actual query for the Puppet API. The query is supposed to ask for data in a given time interval, with a defined start time and end time. On initial startup of the TA the start time is sat to five mintes ago with the following code line; `old = now_datetime.timedelta(minutes=5)`. From there on the start time is supposed to be sat to the time the last query ran, using the variable `ckpt_value`. The end time is always _now_.

I've had the TA ran for days without getting a single event from the extended details input, but when I tried setting the initial start time to a bigger value (`old = now_datetime.timedelta(minutes=500)`), and restarted the Splunk instance, then I got the events I was looking for. Apparantly there is _something_ wrong with how the time intervals for the query is calculated and/or how the `ckpt_value` is sat. Perhaps is has something to do with the timezones? Perhaps if they are not "correct" the time calculations get stuck in a loop or something? I don't know, I haven't looked more into this as of yet. I'm not sure if my solution of setting the initial time to minus 500 minutes will work permanently, or if it will just work _one_ time on initial startup. Any advice is much appreciated!

**Comment by domeger** [comment]
@hettervik - Good point, I made an assumption that everyone would be using GMT in their datacenter and environments. I historically used GMT to maintain consistency, but I like your approach, I can add a filter for the inputs to allow custom changes on interval pulls.

**Comment by archspangler** [comment]
@domeger @mrzarquon ..  I attended your session at .conf 2018..   I am interested in the Puppet Alert actions..  How do I get them?

**Comment by hettervik** [comment]
Hi. The extended logs input have been working fine after I edited the initial start time to look for events in Puppet to 500 minutes, not only just at initial startup, but consistently over time after that. Although it's a kind of "hacky" solution, it did solve my problem. I will close this issue.
