### ISSUE TITLE
Mostly working..

### ISSUE THREAD

**Issue by archspangler** [domeger/SplunkTAforPuppetEnterprise#7]
I have the application working now with some issues.  One thing I would recommend is to update the documentation for the API token to include the token "lifetime" longer than the default of 5 minutes. 

PE Doc:  https://puppet.com/docs/pe/2018.1/rbac_token_auth_intro.html#setting-a-token-specific-lifetime 

I ended up with the following:
curl -k -X POST -H 'Content-Type: application/json' -d '{"login": "<YOUR PE USER NAME>", "password": "<YOUR PE PASSWORD>","lifetime": "9y" }' https://$<HOSTNAME>:4433/rbac-api/v1/auth/token

I also was getting some SSL errors and needed to get the puppet cert from my PE server and add it to my Splunk HF that was running the TA.

My issue now that I cannot seem to resolve.  The facter collection is only grabbing 1 host for facters collection?  I was seeing some messages in the logs about line truncation so I added "TRUNCATE = 0" to the props.conf to troubleshoot.   The truncation messages stopped but I am still only getting facters from one certname each collection run.

When I search for (index=* sourcetype="pe:factors" certname="*") I only have facters from 1 server. 

Here are some of the messages from the logs..

09-07-2018 18:52:10.065 -0400 INFO  TailReader - Will retry path="/opt/splunk/var/log/splunk/splunktaforpuppetenterprise_puppet_enterprise_factors.log.3" after deferring for 10000ms, initCRC changed after being queued (before=0x50d178184950889d, after=0x2b94207408a2eeb0).  File growth rate must be higher than indexing or forwarding rate.

09-07-2018 16:34:26.282 -0400 WARN  LineBreakingProcessor - Truncating line because limit of 10000 bytes has been exceeded with a line length >= 56562 - data_source="/opt/splunk/var/log/splunk/splunktaforpuppetenterprise_puppet_enterprise_factors.log", data_host="xxxxxx", data_sourcetype="splunktaforpuppetenterprise:log"

PE Version 2018.1.3
Splunk 7.3.1

-Archie

Update..

I am seeing the error 'base_modinput.py:log_error:307' in many of the splunktaforpuppetenterprise logfiles.  

-bash-4.2$ pwd
/opt/splunk/var/log/splunk
-bash-4.2$ grep -c 'base_modinput.py:log_error:307' splunktaforpuppetenterprise_*
splunktaforpuppetenterprise_cloud_connect_engine.log:0
splunktaforpuppetenterprise_puppet_enterprise_aggregate_by_resource.log:8817
splunktaforpuppetenterprise_puppet_enterprise_aggregate_details_by_certname.log:8835
splunktaforpuppetenterprise_puppet_enterprise_aggregate_details_by_classes.log:8810
splunktaforpuppetenterprise_puppet_enterprise_extended_details.log:476
splunktaforpuppetenterprise_puppet_enterprise_extended_details.log.1:3439
splunktaforpuppetenterprise_puppet_enterprise_extended_details.log.2:629
splunktaforpuppetenterprise_puppet_enterprise_extended_details.log.3:682
splunktaforpuppetenterprise_puppet_enterprise_extended_details.log.4:1446
splunktaforpuppetenterprise_puppet_enterprise_extended_details.log.5:1099
splunktaforpuppetenterprise_puppet_enterprise_factors.log:22
splunktaforpuppetenterprise_puppet_enterprise_factors.log.1:65
splunktaforpuppetenterprise_puppet_enterprise_factors.log.2:38
splunktaforpuppetenterprise_puppet_enterprise_factors.log.3:65
splunktaforpuppetenterprise_puppet_enterprise_factors.log.4:67
splunktaforpuppetenterprise_puppet_enterprise_factors.log.5:65
splunktaforpuppetenterprise_puppet_enterprise_node_status.log:247
splunktaforpuppetenterprise_puppet_enterprise_node_status.log.1:409
splunktaforpuppetenterprise_puppet_enterprise_node_status.log.2:409
splunktaforpuppetenterprise_puppet_enterprise_node_status.log.3:410
splunktaforpuppetenterprise_puppet_enterprise_node_status.log.4:409
splunktaforpuppetenterprise_puppet_enterprise_node_status.log.5:409
splunktaforpuppetenterprise_puppet_enterprise_status_0d907c823731123e6d4ec9557a1ca45a99ae8ce6b09ef49fd0d23e502de4ab84.log:0
splunktaforpuppetenterprise_puppet_enterprise_status_ff9a5547463478a06ee6f4ff538967494fcab876970afc436cf74d635af03837.log:0
splunktaforpuppetenterprise_util.log:0
-bash-4.2$

**Comment by domeger** [comment]
I have uploaded the latest version that is working on the latest version of Puppet Enterprise and Splunk. Should resolve some of these issues that you are having, you will need to reset your inputs.

**Comment by archspangler** [comment]
Closing this issues due to new version of the TA.
